name: zona44app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8  # Íconos estilo iOS
  flutter_bloc: ^9.1.1     # Implementación del patrón BLoC
  bloc: ^9.0.1             # Biblioteca base del patrón BLoC
  equatable: ^2.0.7        # Comparación de objetos para BLoC
  http: ^1.5.0             # Cliente HTTP
  shared_preferences: ^2.5.3 # Almacenamiento persistente
  cached_network_image: ^3.4.1 # Caché de imágenes
  flutter_neumorphic: ^3.2.0 # Estilo neumórfico
  flutter_animate: ^4.5.2  # Animaciones simples
  flutter_launcher_icons: ^0.14.4 # Íconos de app
  intl_phone_field: ^3.2.0 # Campo teléfono internacional
  url_launcher: ^6.2.6     # Abrir URLs externas
  lottie: ^3.1.0           # Reproducción de animaciones Lottie
  google_sign_in: ^6.2.1   # Autenticación con Google
  flutter_localizations:   # Internacionalización
    sdk: flutter
  intl: ^0.20.2            # Formateo de fechas y números
  google_fonts: ^6.1.0      # Fuentes de Google
  flutter_svg: ^2.0.10      # Soporte para imágenes SVG

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/intro.json
    - assets/animations/home.json
    - assets/images/google.png
    - assets/flags/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/iconv2.png"
